"""Database with Geo_tag

Revision ID: 8937cd3ed220
Revises: ba65cf76c128
Create Date: 2023-09-22 20:08:43.223592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8937cd3ed220'
down_revision: Union[str, None] = 'ba65cf76c128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Desciption', sa.String(), nullable=True),
    sa.Column('geo_tag', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trades', sa.Column('geo_tag_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('hide', sa.String(), nullable=False))
    op.alter_column(
        'trades',
        'price',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="price::integer")
    op.create_foreign_key(None, 'trades', 'tags', ['geo_tag_id'], ['id'])
    op.drop_column('trades', 'geo_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('geo_tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.alter_column('trades', 'price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('trades', 'hide')
    op.drop_column('trades', 'geo_tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
