services:
    - name: trade-service
      entrypoint: http://trade-service:5000/
      inject_token_in_swagger: True
    - name: chat-service
      entrypoint: http://chat-service:5001/
      inject_token_in_swagger: True
    - name: user-service
      entrypoint: http://user-service:5002/
model: |
    [request_definition]
    r = sub, obj, act
    
    [policy_definition]
    p = sub, obj, act
    
    [policy_effect]
    e = some(where (p.eft == allow))
    
    [matchers]
    m = eval(p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)
policies:
    - service: user-service
      resource: /auth/*
      methods: POST
      white_list: true
    - service: user-service
      resource: /users/me
      methods: (GET)|(PATCH)
      rule: r.sub.is_superuser == False
    - service: user-service
      resource: /users/*
      methods: (GET)|(POST)|(PATCH)|(DELETE)
      rule: r.sub.is_superuser == True
    
    - service: trade-service
      resource: /trade
      methods: POST
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /trade
      methods: POST
      rule: r.sub.is_superuser == True
    - service: trade-service
      resource: /trades
      methods: GET
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /trades
      methods: GET
      rule: r.sub.is_superuser == True
    - service: trade-service
      resource: /trades/*
      methods: (GET)|(PATCH)
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /trades/*
      methods: (GET)|(PUT)|(DELETE)|(PATCH)
      rule: r.sub.is_superuser == True
    
    - service: trade-service
      resource: /point_in_range
      methods: GET
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /point_in_range
      methods: GET
      rule: r.sub.is_superuser == True 
    
    - service: trade-service
      resource: /nearest
      methods: GET      
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /nearest
      methods: GET
      rule: r.sub.is_superuser == True
    
    - service: trade-service
      resource: /visualize
      methods: GET
      rule: r.sub.is_superuser == False
    - service: trade-service
      resource: /visualize
      methods: GET
      rule: r.sub.is_superuser == True

    - service: chat-service
      resource: /chatroom
      methods: POST
      rule: r.sub.is_superuser == False
    - service: chat-service
      resource: /chatroom
      methods: POST
      rule: r.sub.is_superuser == True
    
    - service: chat-service
      resource: /last_messages/*
      methods: GET
      rule: r.sub.is_superuser == False
    - service: chat-service
      resource: /last_messages/*
      methods: GET
      rule: r.sub.is_superuser == True
    
    - service: chat-service
      resource: /chat
      methods: GET
      rule: r.sub.is_superuser == False
    - service: chat-service
      resource: /chat
      methods: GET
      rule: r.sub.is_superuser == True

    - service: chat-service
      resource: /ws/*
      methods: WEBSOCKET
      rule: r.sub.is_superuser == False
      
    - service: chat-service
      resource: /ws/*
      methods: WEBSOCKET
      rule: r.sub.is_superuser == True
      
