version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart : always
    environment:
      POSTGRES_PASSWORD: tradedb
      POSTGRES_USER: tradedb
      POSTGRES_DB: tradedb
    ports:
      - "5432:5432"
    networks:
      - custom
  trade-service:
    build:
      context: ../Services/TradeService
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tradedb
      - DB_USERS=tradedb
      - DB_PASS=tradedb
    ports:
      - "5000:5000"
    networks:
      - custom
  # userdb:
  #   container_name: "userdb"
  #   image: postgres:14.1-alpine
  #   restart : always
  #   environment:
  #     POSTGRES_PASSWORD: userdb
  #     POSTGRES_USER: userdb
  #     POSTGRES_DB: userdb
  #   ports:
  #     - "5000:5432"
  #   networks:
  #     - custom
networks:
  custom:
    driver: bridge

 