version: "3.0"
services:
  Tradedb:
    container_name: "Tradedb"
    image: postgis/postgis:13-master
    restart : always
    environment:
      POSTGRES_PASSWORD: tradedb
      POSTGRES_USER: tradedb
      POSTGRES_DB: tradedb
    ports:
      - "5432:5432"
    networks:
      - custom
  trade-service:
    build:
      context: ../Services/TradeService
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DSN=postgresql://tradedb:tradedb@Tradedb:5432/tradedb
    ports:
      - "5000:5000"
    networks:
      - custom
    depends_on:
      - Tradedb
  Chatdb:
    container_name: "Chatdb"
    image: postgres:14.1-alpine
    restart : always
    environment:
      POSTGRES_PASSWORD: chatdb
      POSTGRES_USER: chatdb
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    networks:
      - custom
  chat-service:
    build:
      context: ../Services/ChatService
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://chatdb:chatdb@Chatdb:5432/chatdb
    ports:
      - "5001:5001"
    networks:
      - custom
    depends_on:
      - Chatdb
  Userdb:
    container_name: "userdb"
    image: postgres:14.1-alpine
    restart : always
    environment:
      POSTGRES_PASSWORD: userdb
      POSTGRES_USER: userdb
      POSTGRES_DB: userdb
    ports:
      - "5034:5432"
    networks:
      - custom
  user-service:
    build:
      context: ../Services/UserService
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://userdb:userdb@Userdb:5432/userdb
    ports:
      - "5002:5002"
    networks:
      - custom
    depends_on:
      - Userdb
networks:
  custom:
    driver: bridge

 