version: "3.0"
services:
  Tradedb:
    container_name: "db"
    image: postgis/postgis:13-master
    restart : always
    environment:
      POSTGRES_PASSWORD: tradedb
      POSTGRES_USER: tradedb
      POSTGRES_DB: tradedb
    ports:
      - "5432:5432"
    networks:
      - custom
  trade-service:
    build:
      context: ../Services/TradeService
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DSN=postgresql://tradedb:tradedb@Tradedb:5432/tradedb
    ports:
      - "5000:5000"
    networks:
      - custom
    depends_on:
      - Tradedb
  # userdb:
  #   container_name: "userdb"
  #   image: postgres:14.1-alpine
  #   restart : always
  #   environment:
  #     POSTGRES_PASSWORD: userdb
  #     POSTGRES_USER: userdb
  #     POSTGRES_DB: userdb
  #   ports:
  #     - "5000:5432"
  #   networks:
  #     - custom
networks:
  custom:
    driver: bridge

 